dist: trusty
sudo: false

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk=2.1.11-1

language: ruby
cache:
  directories:
  - vendor/bundle
  - vendor/cookbooks
bundler_args: --path=$PWD/vendor/bundle
rvm:
  - 2.2
script:
  - chef exec cookstyle
  - chef exec foodcritic --progress -f any .

services: docker
env:
  matrix:
    - INSTANCE=default12-ubuntu-14
    - INSTANCE=default12-centos-6
    - INSTANCE=default12-centos-7
    - INSTANCE=pip-install12-ubuntu-14
    - INSTANCE=pip-install12-centos-6
    - INSTANCE=pip-install12-centos-7
    - INSTANCE=default13-ubuntu-14
    - INSTANCE=default13-centos-6
    - INSTANCE=default13-centos-7
    - INSTANCE=pip-install13-ubuntu-14
    - INSTANCE=pip-install13-centos-6
    - INSTANCE=pip-install13-centos-7

script:
  - chef exec cookstyle
  - chef exec foodcritic --progress -f any .
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml chef exec kitchen test ${INSTANCE}
  - cat .kitchen/logs/kitchen.log

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )

matrix:
  allow_failures:
    - env: INSTANCE=default12-ubuntu-14
    - env: INSTANCE=default12-centos-6
    - env: INSTANCE=default12-centos-7
    - env: INSTANCE=pip-install12-ubuntu-14
    - env: INSTANCE=pip-install12-centos-6
    - env: INSTANCE=pip-install12-centos-7
    - env: INSTANCE=default13-ubuntu-14
    - env: INSTANCE=default13-centos-6
    - env: INSTANCE=default13-centos-7
    - env: INSTANCE=pip-install13-ubuntu-14
    - env: INSTANCE=pip-install13-centos-6
    - env: INSTANCE=pip-install13-centos-7
  include:
    - script:
      - chef exec cookstyle
      - chef exec foodcritic --progress -f any .
      env: LINT=1
